spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.16.195.130:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: root
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.16.195.133:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: root


swagger:
  enabled: true
  docket:
    mybatis-plus-demo-model:
      title: demo-api
      base-package: com.beikai.springbootmybatisplus.ReadAndWriterSpilt.controller

