banner:
  charset: utf-8
server:
  tomcat:
    uri-encoding: UTF-8

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8
    # 连接池的配置信息
    # 初始化大小，最小，最大
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    minIdle: 5
    initialSize: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000

    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

## 默认的数据源
master:
  datasource:
    url: jdbc:mysql://192.168.2.224:3306/mytest2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver


## 另一个的数据源
cluster:
  datasource:
    url: jdbc:mysql://192.168.2.224:3306/mytest3?useUnicode=true&characterEncoding=utf8&&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

## 打印SQL语句
logging:
  level:
    com.beikai.MutilOfDruid.dao: debug


swagger:
  enabled: true
  docket:
    mybatis-plus-demo-model:
      title: demo-api
      base-package: com.beikai.springbootmybatisplus.ReadAndWriterSpilt.controller

