spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.195.130:3306/mytest?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
    username: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 180000
      pool-name: beikai_hikaricp_pool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


swagger:
  enabled: true
  docket:
    mybatis-plus-demo-model:
      title: demo-api
      base-package: com.beikai.springbootmybatisplus.ReadAndWriterSpilt.controller